In [1]:
# If we are not using Jupyter Notebook, don't take into account the two following lines.
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [26]:
import torch
torch.cuda.is_available() 

True

In [27]:
x = torch.Tensor(2,3) 
y=torch.Tensor(2,3) 
x = x.cuda()
y = y.cuda()
x+y
#x
#y

RuntimeError: cuda runtime error (48) : no kernel image is available for execution on the device at /opt/conda/conda-bld/pytorch_1512387374934/work/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu:301

In [5]:
z = torch.rand(5, 3)
z
x = torch.Tensor(5, 3)
x


 0.1408  0.7507  0.3975
 0.8047  0.1675  0.6454
 0.1726  0.0606  0.5418
 0.3614  0.1386  0.9070
 0.7553  0.0888  0.3351
[torch.FloatTensor of size 5x3]


 2.8665e-27  4.5737e-41  2.8665e-27
 4.5737e-41  0.0000e+00  9.8091e-45
-2.2976e+14  4.5736e-41  0.0000e+00
 0.0000e+00  4.4842e-44  1.6255e-43
 1.7937e-43  0.0000e+00  1.7937e-43
[torch.FloatTensor of size 5x3]

In [6]:
x+z
x[:, 1]
y = torch.Tensor(5, 3)
torch.add(x, z, out=y)
y


 1.4077e-01  7.5067e-01  3.9752e-01
 8.0469e-01  1.6749e-01  6.4535e-01
-2.2976e+14  6.0552e-02  5.4180e-01
 3.6139e-01  1.3862e-01  9.0701e-01
 7.5532e-01  8.8787e-02  3.3506e-01
[torch.FloatTensor of size 5x3]


1.00000e-41 *
  4.5737
  0.0000
  4.5736
  0.0045
  0.0000
[torch.FloatTensor of size 5]


 1.4077e-01  7.5067e-01  3.9752e-01
 8.0469e-01  1.6749e-01  6.4535e-01
-2.2976e+14  6.0552e-02  5.4180e-01
 3.6139e-01  1.3862e-01  9.0701e-01
 7.5532e-01  8.8787e-02  3.3506e-01
[torch.FloatTensor of size 5x3]


 1.4077e-01  7.5067e-01  3.9752e-01
 8.0469e-01  1.6749e-01  6.4535e-01
-2.2976e+14  6.0552e-02  5.4180e-01
 3.6139e-01  1.3862e-01  9.0701e-01
 7.5532e-01  8.8787e-02  3.3506e-01
[torch.FloatTensor of size 5x3]

In [18]:
## 注意，如果一个numpy向量引用一个torch向量，那么torch向量改变会导致numpy向量改变。
## 反之，numpy向量改变一样会导致torch改变。但是！！这必须是numpy求和函数add，而不能是普通加。普通加不能
## 使得torch随之改变。

z = torch.ones(5)
b = z.numpy()
b
z.add_(1)
b
np.add(b, 1, out = b)
z
b
b = b + 1
b
z

array([ 1.,  1.,  1.,  1.,  1.], dtype=float32)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

array([ 2.,  2.,  2.,  2.,  2.], dtype=float32)

array([ 3.,  3.,  3.,  3.,  3.], dtype=float32)


 3
 3
 3
 3
 3
[torch.FloatTensor of size 5]

array([ 3.,  3.,  3.,  3.,  3.], dtype=float32)

array([ 4.,  4.,  4.,  4.,  4.], dtype=float32)


 3
 3
 3
 3
 3
[torch.FloatTensor of size 5]

In [24]:
## 反之如果是torch索引了numpy，效果是一样的。一方改变都会导致另一方改变，
## 只是不能使用普通加，必须是numpy函数add。

import numpy as np

c = np.ones(5)
e = torch.from_numpy(c)
np.add(c, 1, out = c)
e
e.add_(1)
c
c = c+1 # 这语句导致二者完全脱离互相牵制的的关系。以后改谁另一个都不理。
c
e
e.add_(-2)
e
c

array([ 2.,  2.,  2.,  2.,  2.])


 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]


 3
 3
 3
 3
 3
[torch.DoubleTensor of size 5]

array([ 3.,  3.,  3.,  3.,  3.])

array([ 4.,  4.,  4.,  4.,  4.])


 3
 3
 3
 3
 3
[torch.DoubleTensor of size 5]


 1
 1
 1
 1
 1
[torch.DoubleTensor of size 5]


 1
 1
 1
 1
 1
[torch.DoubleTensor of size 5]

array([ 4.,  4.,  4.,  4.,  4.])

In [16]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
b

array([ 2.,  2.,  2.,  2.,  2.])


 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]

In [20]:
from torch.autograd import Variable
x = Variable(torch.ones(2, 2), requires_grad = True)
y = x + 2
y.grad_fn

In [24]:
z = y * y * 3
z2 = y * y # 按元素乘
z2
z
out = z.mean()
out

Variable containing:
 9  9
 9  9
[torch.FloatTensor of size 2x2]

Variable containing:
 27  27
 27  27
[torch.FloatTensor of size 2x2]

Variable containing:
 27
[torch.FloatTensor of size 1]

In [27]:
#out.backward()
x.grad

Variable containing:
 4.5000  4.5000
 4.5000  4.5000
[torch.FloatTensor of size 2x2]

In [36]:
x = torch.randn(3)
x = Variable(x, requires_grad = True)
y = x * 2
while y.data.norm() < 1000:
    y = y * 2 + y.mean()
x, y

(Variable containing:
 -1.6451
  0.5014
  0.1789
 [torch.FloatTensor of size 3], Variable containing:
 -1745.5042
 -1195.9952
 -1278.5574
 [torch.FloatTensor of size 3])

In [37]:
gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
y.backward(gradients)
x.grad

Variable containing:
 1535.6705
 1766.0704
 1510.0962
[torch.FloatTensor of size 3]

In [34]:
rea = 3
def tr (x):
    rea = 2
    return(x)

print(tr(1))
rea # 3. Local value can't change the global one.

1


3

In [35]:
rea = [3, 4]
def tr (x):
    rea[1] = 2
    return(x)

print(tr(1))
rea # [3, 2]. If list, change is in place.

1


[3, 2]

In [36]:
rea = 3
def tr (x):
    x = rea + 2
    rea = 2
    return(x)
# This can't run.
# UnboundLocalError: local variable 'rea' referenced before assignment
print(tr(1))

UnboundLocalError: local variable 'rea' referenced before assignment

In [42]:
rea = 3
def tr (x):
    rea = rea + 2 # Doesn't work either.
    print(rea)
    return(x)
print(rea)
tr(2)

3


UnboundLocalError: local variable 'rea' referenced before assignment

In [51]:
x = np.arange(3, 5)
y = np.arange(6, 11)
y[x]

array([ 9, 10])